version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cairx_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: cairx_frontend
    ports:
      - "8501:8501" 
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
